# Generated by Django 4.2 on 2023-04-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('it_proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('stock', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='static/upload')),
                ('suc_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_proveedor.suc_empresa')),
            ],
        ),
    ]
