# Generated by Django 4.2 on 2023-04-10 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_proveedor', '0001_initial'),
        ('it_product', '0003_alter_productos_suc_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='suc_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_proveedor.suc_empresa'),
        ),
    ]
